In [1]:
import pandas as pd
import numpy as np

In [9]:
df=pd.read_csv(r"Datasets/spam.csv", encoding = "ISO-8859-1", engine = "python")
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [10]:
for col in ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']:
    df=df.drop(col,axis=1)
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
df.rename(columns={'v1':'Category','v2':'Message'},inplace=True)

In [12]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [13]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [14]:
df.shape

(5572, 3)

In [15]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [17]:
X_train.shape

(4457,)

In [18]:
X_test.shape

(1115,)

In [19]:
X_train[:4]

4624                             I'm on the bus. Love you
4769    CHEERS LOU! YEAH WAS A GOODNITE SHAME U NEVA C...
993     The Xmas story is peace.. The Xmas msg is love...
1574    My sis is catching e show in e afternoon so i'...
Name: Message, dtype: object

In [20]:
type(y_train)

pandas.core.series.Series

In [21]:
y_train[:4]

4624    0
4769    0
993     0
1574    0
Name: spam, dtype: int64

In [22]:
type(X_train.values)

numpy.ndarray

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7733 sparse matrix of type '<class 'numpy.int64'>'
	with 59372 stored elements in Compressed Sparse Row format>

In [24]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [25]:
X_train_cv.shape

(4457, 7733)

In [37]:
v.get_feature_names_out()[4931]

'on'

In [27]:
v.vocabulary_

{'on': 4931,
 'the': 6790,
 'bus': 1579,
 'love': 4227,
 'you': 7685,
 'cheers': 1783,
 'lou': 4221,
 'yeah': 7657,
 'was': 7362,
 'goodnite': 3217,
 'shame': 6052,
 'neva': 4749,
 'came': 1639,
 'ya': 7642,
 'gailxx': 3090,
 'xmas': 7625,
 'story': 6492,
 'is': 3764,
 'peace': 5129,
 'msg': 4613,
 'miracle': 4504,
 'jesus': 3837,
 'hav': 3382,
 'blessed': 1396,
 'month': 4574,
 'ahead': 877,
 'amp': 954,
 'wish': 7515,
 'merry': 4454,
 'my': 4661,
 'sis': 6170,
 'catching': 1702,
 'show': 6114,
 'in': 3662,
 'afternoon': 859,
 'so': 6269,
 'not': 4829,
 'watching': 7374,
 'her': 3433,
 'wan': 7344,
 'watch': 7370,
 'today': 6914,
 'or': 4971,
 'tmr': 6904,
 'lor': 4207,
 'can': 1643,
 'send': 6002,
 'pic': 5203,
 'if': 3619,
 'like': 4114,
 'midnight': 4474,
 'at': 1120,
 'earliest': 2536,
 'wats': 7381,
 'ur': 7169,
 'opinion': 4960,
 'abt': 772,
 'him': 3457,
 'and': 967,
 'how': 3540,
 'character': 1751,
 'yar': 7649,
 'but': 1586,
 'they': 6814,
 'say': 5924,
 'got': 3227,
 'some'

In [28]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
np.where(X_train_np[0]!=0)

(array([1579, 4227, 4931, 6790, 7685], dtype=int64),)

In [30]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [31]:
X_test_cv = v.transform(X_test)

In [32]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       963
           1       0.97      0.92      0.95       152

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [33]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [34]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [35]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [36]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       963
           1       0.97      0.92      0.95       152

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

